import type { Metadata } from "next";
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{padding: '12px 20px', borderBottom: '1px solid #e6e6e6', marginBottom: 20}}>
          <nav style={{display: 'flex', gap: 16, alignItems: 'center'}}>
            <Link href="/">Inicio</Link>
            <Link href="/reading-list">Mi lista de lectura</Link>
          </nav>
        </header>

        <main style={{padding: '0 20px'}}>{children}</main>
      </body>
    </html>
  );
}
